import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { Github, Twitter } from "lucide-react";
import LogoMark from "./components/logo-mark";
import LogoText from "./components/logo-text";
import Link from "next/link";
import "./globals.css";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigation = [
  { name: "Latest", href: "/" },
  { name: "About", href: "/about" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} antialiased bg-base text-text`}
      >
        <header className="max-w-[1280px] w-full mx-auto px-4 pt-8 flex items-center justify-between pb-8">
          <div className="flex gap-2">
            <LogoMark className="w-[66px] text-[#ba43f7] pb-[8px]" />
            <LogoText className="w-[226px] text-white" />
          </div>

          <nav className="hidden sm:flex gap-6">
            {navigation.map((item) => (
              <Link
                key={item.name}
                href={item.href}
                className="flex items-center text-xl text-muted-foreground hover:text-primary"
              >
                {item.name}
              </Link>
            ))}
          </nav>
        </header>

        <div className="min-h-screen max-w-[1280px] mx-auto">
        {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}

function Footer() {
  return (
    <footer className="border-t border-surface1 bg-background mt-24">
      <div className="container max-w-[1280px] mx-auto flex flex-col items-center justify-between gap-4 py-10 md:h-24 md:flex-row md:py-0">
        <div className="flex flex-col items-center gap-4 px-8 md:flex-row md:gap-2 md:px-0">
          <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
            Copyright © {new Date().getFullYear()} Tech Cringe. All
            rights reserved.
          </p>
        </div>
        <div className="flex items-center space-x-4">
          <Link
            href="https://github.com/tehccringe"
            target="_blank"
            rel="noreferrer"
          >
            <Github className="h-5 w-5 text-muted-foreground hover:text-foreground" />
            <span className="sr-only">GitHub</span>
          </Link>
          <Link
            href="https://x.com/tehccringe"
            target="_blank"
            rel="noreferrer"
          >
            <svg
              className="size-5 fill-current hover:text-foreground"
              role="img"
              viewBox="0 0 24 24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <title>X</title>
              <path d="M18.901 1.153h3.68l-8.04 9.19L24 22.846h-7.406l-5.8-7.584-6.638 7.584H.474l8.6-9.83L0 1.154h7.594l5.243 6.932ZM17.61 20.644h2.039L6.486 3.24H4.298Z" />
            </svg>
            <span className="sr-only">Twitter</span>
          </Link>
        </div>
      </div>
    </footer>
  );
}
